name: Install
on:
  push: {branches: main}
  pull_request: {branches: main}

jobs:
  test:
    runs-on: ubuntu-latest
    name: setup
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: exit 0
  e2e:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref != 'refs/heads/main'
    steps:
      - uses: cinotify/github-action@staging
        with:
          to: "invalid email"
          subject: "staging cinotify github action"
          body: "<em>This is a notification from GitHub actions.</em>"
          type: "text/html"
